language: node_js
sudo: false
node_js:
# https://github.com/sass/node-sass/issues/490
#  - "0.11"
  - "0.10"
before_script:
  - gem install scss-lint
  - npm install -g gulp
script: gulp
# See https://github.com/travis-ci/travis-core/pull/137
branches:
  only:
    - gh-pages
